### PR TITLE
Fix/value not found type

### PR DESCRIPTION
**Pull request by CasperCDR**
Fixed typo in classname

### CODE REVIEW

**Comment by alastair** [comment]
thanks!

**Comment by CasperCDR** [comment]
Somehow this merge is not reflected in the master branch.

**Comment by alastair** [comment]
I see it here: https://github.com/trompamusic/trompa-ce-client/commits/master

**Comment by CasperCDR** [comment]
The commit is visible, but the code is not altered. I still see the typo in the master branch.

**Pull request merged**
