### PR TITLE
Updated arguments for person as per list

### PR DESCRIPTION
**Pull request by pc2752**
Updated mutations and tests for finalised arguments for person, as listed in https://docs.google.com/document/d/1B1O2tqaubbEHzXSWhvSDYqYu2lwdNKg4Vy04ukMfrUU/edit?pli=1#. Made update mutation more elegant. Name is optional, as suggested in the document.

### CODE REVIEW

**Comment by pc2752** [comment]
Could you confirm if publisher should be in the arguments? Or can it be removed? It's not there in the Modelling Discussions

**Comment by alastair** [comment]
We have no need for publisher at the moment. Let's leave it out until someone comes up with a specific need.

**Comment by alastair** [comment]
Note that you'll have to rebase against master due to other PRs that were merged.

Make sure you're careful with files you add and delete. I typically use `git add <file>` individually for each file that I need to add, to avoid the problem of adding additional files. I see that you added `tests/data/person/._EXPECTED_PERSON.txt` which is probably a temporary file from your text editor.

**Comment by pc2752** [comment]
Resolved issues, conflicts do not show up in the terminal, not sure why they're here.

**Comment by alastair** [comment]
did you `git fetch` to download the latest changes to your local version?

**Comment by pc2752** [comment]
Yes, I tried git fetch, not getting conflicts on my end.

**Pull request merged**
